// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    Preview: typeof import('./components/Preview.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
